export const languageRegister = {
      vi: {
        subtitle: "Tạo tài khoản để nhận nhiều ưu đãi hấp dẫn",
        requirements: ["Ít nhất 8 ký tự", "Chứa chữ hoa", "Chứa chữ thường", "Chứa số"],
        passwordMismatch: "Mật khẩu xác nhận không khớp",
        acceptTermsError: "Vui lòng đồng ý với điều khoản sử dụng",
        registerFailed: "Đăng ký thất bại. Vui lòng thử lại.",
        genericError: "Có lỗi xảy ra. Vui lòng thử lại.",
        fullName: "Họ và tên",
        fullNamePlaceholder: "Nguyễn Văn A",
        phone: "Số điện thoại",
        password: "Mật khẩu",
        passwordPlaceholder: "Nhập mật khẩu",
        confirmPassword: "Xác nhận mật khẩu",
        confirmPasswordPlaceholder: "Nhập lại mật khẩu",
        agreePrefix: "Tôi đồng ý với",
        terms: "Điều khoản sử dụng",
        and: "và",
        privacy: "Chính sách bảo mật",
        processing: "Đang xử lý...",
        hasAccount: "Đã có tài khoản?",
      },
      en: {
        subtitle: "Create an account to receive exclusive offers",
        requirements: ["At least 8 characters", "Contains uppercase letter", "Contains lowercase letter", "Contains number"],
        passwordMismatch: "Password confirmation does not match",
        acceptTermsError: "Please agree to the terms of use",
        registerFailed: "Registration failed. Please try again.",
        genericError: "Something went wrong. Please try again.",
        fullName: "Full name",
        fullNamePlaceholder: "Nguyen Van A",
        phone: "Phone number",
        password: "Password",
        passwordPlaceholder: "Enter password",
        confirmPassword: "Confirm password",
        confirmPasswordPlaceholder: "Enter password again",
        agreePrefix: "I agree to the",
        terms: "Terms of use",
        and: "and",
        privacy: "Privacy policy",
        processing: "Processing...",
        hasAccount: "Already have an account?",
      },
      zh: {
        subtitle: "创建账号以获取更多优惠",
        requirements: ["至少8个字符", "包含大写字母", "包含小写字母", "包含数字"],
        passwordMismatch: "两次输入的密码不一致",
        acceptTermsError: "请同意使用条款",
        registerFailed: "注册失败，请重试。",
        genericError: "发生错误，请重试。",
        fullName: "姓名",
        fullNamePlaceholder: "Nguyen Van A",
        phone: "电话号码",
        password: "密码",
        passwordPlaceholder: "请输入密码",
        confirmPassword: "确认密码",
        confirmPasswordPlaceholder: "请再次输入密码",
        agreePrefix: "我同意",
        terms: "使用条款",
        and: "和",
        privacy: "隐私政策",
        processing: "处理中...",
        hasAccount: "已有账号？",
      },
    };