import {
  BookOpen,
  BriefcaseBusiness,
  CalendarCheck,
  CreditCard,
  Crown,
  FileText,
  Gift,
  HeartHandshake,
  HelpCircle,
  Landmark,
  Leaf,
  MessageCircle,
  PackageCheck,
  Percent,
  Phone,
  RefreshCcw,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Star,
  Stethoscope,
  Truck,
  Users,
  type LucideIcon,
} from "lucide-react";

export const contentIconMap: Record<string, LucideIcon> = {
  BookOpen,
  BriefcaseBusiness,
  CalendarCheck,
  CreditCard,
  Crown,
  FileText,
  Gift,
  HeartHandshake,
  HelpCircle,
  Landmark,
  Leaf,
  MessageCircle,
  PackageCheck,
  Percent,
  Phone,
  RefreshCcw,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Star,
  Stethoscope,
  Truck,
  Users,
};

export const getContentIcon = (icon?: string) => contentIconMap[icon || ""] || FileText;
